ah_dc            = "ams1"
ah_token         = "YOURE_TOP_SECRET_TOKEN"
ah_machine_type  = "start-xs"
ah_image_type    = "centos-7-x64"
ah_hdd           = "ssd2-ams1"
ah_fp            = "YOURE_TOP_SECRET_SSH_HASH"
private_key_path = "/root/.ssh/id_rsa.pub"
